import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Circle } from "../../components/Circle";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Welcome this is the homepage</h1>
        <Circle text="A sample text">
          <h1>Hey !!!!</h1>
          <Image src="/next.svg" alt="logo" width='100' height="100"/>
        </Circle>

        <Circle>hello this a sample</Circle>
      </main>
    </>
  );
}
